apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  namespace: exam2
  labels:
    app: mysql
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: pay-db
        image: stigma137/mysql:latest
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
 name: mysql
 namespace: exam2
 labels:
  app: mysql
spec:
 type: ClusterIP
 selector:
  app: mysql
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306